[package]
name = "houston"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
houston-api = { path = "../houston-api" }
houston-ui = { path = "../houston-ui" }
houston-core = { path = "../houston-core" }
tokio = { version = "1.37.0", features = ["full"] }
crossterm = "0.29"
ratatui = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
