[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
readme = "README.md"
version = "0.1.10"
repository = "https://github.com/noetic-sys/houston"
homepage = "https://github.com/noetic-sys/houston"
authors = ["Kyle Sandell <kasandell@gmail.com>"]
description = "Terminal UI for managing GitHub Actions workflows and deployments"
keywords = ["tui", "github", "cli", "devops", "terminal"]
categories = ["command-line-utilities", "development-tools"]



[workspace.dependencies]
ratatui = "0.29.0"

[profile.dist]
inherits = "release"
lto = "thin"