[package]
name = "houston-api"
edition = "2021"
license = "MIT"
readme = "README.md"
version = "0.1.9"
repository = "https://www.github.com/kasandell/houston"
authors = ["Kyle Sandell"]
description = "Houston API crate"

[dependencies]
octocrab = "0.29.0"
async-trait = "0.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }