[package]
name = "houston-api"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description.workspace = true
publish = false

[dependencies]
octocrab = "0.29.0"
async-trait = "0.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
base64 = "0.21"
serde_yaml = "0.9"